import type { WorkOrder } from '@/services/auditService';

/**
 * Local fallback dataset used when Supabase is not configured. The first entry
 * is the seeded flagship work order `MPLADS-2026-BLR-0042` so the alerts table
 * and deep-dive views populate immediately without a live backend.
 */
export const demoWorkOrders: WorkOrder[] = [
  {
    id: 'demo-0042',
    work_id: 'MPLADS-2026-BLR-0042',
    title: 'Stormwater drain reconstruction — Koramangala 4th Block',
    ward_name: 'Koramangala',
    contractor: 'Sri Venkateshwara Infra Pvt Ltd',
    agency: 'BBMP',
    work_category: 'Stormwater Drain',
    budget: 12800000,
    risk_score: 92,
    risk_level: 'high',
    status: 'flagged',
    funds_frozen: 0,
    date: '2026-08-21',
    created_at: '2026-08-21T06:30:00.000Z',
  },
  {
    id: 'demo-0043',
    work_id: 'MPLADS-2026-BLR-0043',
    title: 'Arterial road asphalt overlay — Indiranagar 100ft Road',
    ward_name: 'Indiranagar',
    contractor: 'Deccan Roadways & Builders',
    agency: 'BBMP',
    work_category: 'Road Asphalt',
    budget: 9600000,
    risk_score: 78,
    risk_level: 'high',
    status: 'under_review',
    funds_frozen: 0,
    date: '2026-08-18',
    created_at: '2026-08-18T05:10:00.000Z',
  },
  {
    id: 'demo-0044',
    work_id: 'MPLADS-2026-BLR-0044',
    title: 'LED street lighting upgrade — Jayanagar 9th Block',
    ward_name: 'Jayanagar',
    contractor: 'Prakash Electricals',
    agency: 'BESCOM',
    work_category: 'Street Lighting',
    budget: 4200000,
    risk_score: 64,
    risk_level: 'medium',
    status: 'flagged',
    funds_frozen: 0,
    date: '2026-08-15',
    created_at: '2026-08-15T08:45:00.000Z',
  },
  {
    id: 'demo-0045',
    work_id: 'MPLADS-2026-BLR-0045',
    title: 'Community hall renovation — Malleshwaram',
    ward_name: 'Malleshwaram',
    contractor: 'Kaveri Constructions',
    agency: 'KSCP',
    work_category: 'Community Hall',
    budget: 7300000,
    risk_score: 71,
    risk_level: 'medium',
    status: 'frozen',
    funds_frozen: 7300000,
    date: '2026-08-11',
    created_at: '2026-08-11T04:20:00.000Z',
  },
  {
    id: 'demo-0046',
    work_id: 'MPLADS-2026-BLR-0046',
    title: 'Park development & fencing — HSR Layout Sector 2',
    ward_name: 'HSR Layout',
    contractor: 'GreenScape Developers',
    agency: 'BBMP',
    work_category: 'Park Development',
    budget: 5400000,
    risk_score: 41,
    risk_level: 'low',
    status: 'cleared',
    funds_frozen: 0,
    date: '2026-08-08',
    created_at: '2026-08-08T09:00:00.000Z',
  },
  {
    id: 'demo-0047',
    work_id: 'MPLADS-2026-BLR-0047',
    title: 'Water supply pipeline extension — Whitefield',
    ward_name: 'Whitefield',
    contractor: 'AquaFlow Systems',
    agency: 'BWSSB',
    work_category: 'Water Supply',
    budget: 15200000,
    risk_score: 85,
    risk_level: 'high',
    status: 'flagged',
    funds_frozen: 0,
    date: '2026-08-05',
    created_at: '2026-08-05T07:15:00.000Z',
  },
  {
    id: 'demo-0048',
    work_id: 'MPLADS-2026-BLR-0048',
    title: 'Sanitation & solid-waste yard upgrade — RR Nagar',
    ward_name: 'RR Nagar',
    contractor: 'CleanCity Services',
    agency: 'Panchayat',
    work_category: 'Sanitation',
    budget: 3100000,
    risk_score: 53,
    risk_level: 'medium',
    status: 'under_review',
    funds_frozen: 0,
    date: '2026-08-02',
    created_at: '2026-08-02T06:00:00.000Z',
  },
];

export function findDemoWorkOrder(workId: string): WorkOrder | undefined {
  return demoWorkOrders.find((w) => w.work_id === workId);
}
