import { supabase, isSupabaseConfigured } from '@/lib/supabaseClient';
import { alerts } from '@/lib/mockData';
import { calculateRisk } from '@/ml/anomalyEngine';

const DEMO_KEY = 'drishti-demo-work-orders-v2';
const DEMO_VISION_KEY = 'drishti-demo-vision-v2';
const DEMO_AUDIT_KEY = 'drishti-demo-audit-trail-v2';

export interface GraphNode { id:string; label:string; type:'mp'|'contractor'|'subcontractor'|'bank'; x:number; y:number; risk_score:number; }
export interface GraphEdge { id:string; from_node:string; to_node:string; label:string; is_suspicious:boolean; }
export interface CollusionNetwork { nodes:GraphNode[]; edges:GraphEdge[]; }
export interface VisionForensics { id:string; work_id:string; contractor_photo_url:string|null; gps_coordinates:string; gps_verified:boolean; timestamp_verified:boolean; shadow_geometry_score:number; duplicate_detected:boolean; ai_status:string; created_at:string; updated_at:string; }
export interface AIPipelineResponse { success:boolean; work_id:string; status:string; funds_frozen:number|boolean; message:string; mode?:string; shadow_geometry_score?:number; gps_verified?:boolean; timestamp_verified?:boolean; duplicate_detected?:boolean; risk_score?:number; risk_level?:string; model?:string; explanations?:string[]; }
export interface WorkOrder { id:string; work_id:string; title:string; ward_name:string; contractor:string; agency:string; work_category:string; budget:number; risk_score:number; risk_level:'high'|'medium'|'low'; status:'flagged'|'frozen'|'under_review'|'cleared'|'PENDING_AUDIT'; funds_frozen:number; date:string; created_at:string; mp_name?:string; constituency?:string; total_expenditure?:number; total_payments_released?:number; physical_progress_percentage?:number; expected_progress_percentage?:number; target_date?:string; delay_days?:number; duplicate_similarity?:number; contractor_repeat_rate?:number; is_demo_data?:boolean; }
export interface AuditTrailEntry { audit_id:string; work_id:string|null; actor:string; action_executed:string; justification_log:string; created_at:string; }

const DEMO_NETWORK:CollusionNetwork={nodes:[{id:'mp1',label:'MP — Oversight',type:'mp',x:360,y:80,risk_score:45},{id:'con1',label:'Contractor A',type:'contractor',x:180,y:210,risk_score:92},{id:'con2',label:'Contractor B',type:'contractor',x:540,y:210,risk_score:76},{id:'sub1',label:'Vendor Cluster',type:'subcontractor',x:270,y:350,risk_score:88},{id:'bank1',label:'Shared Account',type:'bank',x:450,y:350,risk_score:91}],edges:[{id:'e1',from_node:'mp1',to_node:'con1',label:'award',is_suspicious:false},{id:'e2',from_node:'mp1',to_node:'con2',label:'award',is_suspicious:false},{id:'e3',from_node:'con1',to_node:'sub1',label:'sub-contract',is_suspicious:true},{id:'e4',from_node:'con2',to_node:'bank1',label:'payment',is_suspicious:true},{id:'e5',from_node:'sub1',to_node:'bank1',label:'transfer',is_suspicious:true}]};
const demoOrders=():WorkOrder[]=>{const stored=localStorage.getItem(DEMO_KEY);if(stored)return JSON.parse(stored) as WorkOrder[];const seeded=alerts.map(a=>({id:a.id,work_id:a.id,title:a.workTitle,ward_name:a.wardName,contractor:a.contractor,agency:a.agency,work_category:a.workCategory,budget:a.fundAmount,risk_score:a.riskScore,risk_level:a.riskLevel,status:a.status,funds_frozen:a.status==='frozen'?a.fundAmount:0,date:a.date,created_at:`${a.date}T09:00:00.000Z`,is_demo_data:true}));localStorage.setItem(DEMO_KEY,JSON.stringify(seeded));return seeded;};
const saveDemo=(o:WorkOrder[])=>localStorage.setItem(DEMO_KEY,JSON.stringify(o));
const riskFor=(s:number):WorkOrder['risk_level']=>s>=75?'high':s>=50?'medium':'low';
const withTimeout=async<T>(p:PromiseLike<T>,ms=7000):Promise<T>=>Promise.race([Promise.resolve(p),new Promise<T>((_,r)=>setTimeout(()=>r(new Error('Backend request timed out; continuing in demo-safe mode.')),ms))]);

export async function fetchWorkOrders():Promise<WorkOrder[]>{if(isSupabaseConfigured&&supabase){try{const{data,error}=await supabase.from('work_orders').select('*').order('risk_score',{ascending:false});if(!error&&data?.length)return data as WorkOrder[];}catch{}}return demoOrders().sort((a,b)=>b.risk_score-a.risk_score);}

export async function upsertUploadedWorkOrders(rows:Array<Partial<WorkOrder>>):Promise<{persisted:boolean;count:number;error?:string}>{
 const payload=rows.map(r=>{const base={...r,budget:Math.max(0,Number(r.budget||0)),total_expenditure:Math.max(0,Number(r.total_expenditure||0)),total_payments_released:Math.max(0,Number(r.total_payments_released||0))};const scored=calculateRisk(base);return {work_id:r.work_id,title:r.title||'Untitled work',ward_name:r.ward_name||'Unspecified',contractor:r.contractor||'Unspecified',agency:r.agency||'Unspecified',work_category:r.work_category||'Infrastructure',budget:base.budget,risk_score:scored.riskScore,risk_level:riskFor(scored.riskScore),status:'PENDING_AUDIT' as const,funds_frozen:0,date:r.date||new Date().toISOString().slice(0,10),mp_name:r.mp_name||null,constituency:r.constituency||null,total_expenditure:base.total_expenditure,total_payments_released:base.total_payments_released,physical_progress_percentage:Number(r.physical_progress_percentage||0),expected_progress_percentage:Number(r.expected_progress_percentage||0),target_date:r.target_date||null,delay_days:Number(r.delay_days||0),duplicate_similarity:Number(r.duplicate_similarity||0),contractor_repeat_rate:Number(r.contractor_repeat_rate||0),is_demo_data:r.is_demo_data!==false};});
 if(isSupabaseConfigured&&supabase){const{error}=await supabase.from('work_orders').upsert(payload,{onConflict:'work_id'});if(!error)return{persisted:true,count:payload.length};console.error('Upload persistence failed:',error);}
 const current=demoOrders(),byId=new Map(current.map(r=>[r.work_id,r]));payload.forEach(r=>byId.set(r.work_id!,{...r,id:r.work_id!,created_at:new Date().toISOString()} as WorkOrder));saveDemo(Array.from(byId.values()));return{persisted:false,count:payload.length,error:'Backend persistence unavailable; local demo state retained.'};
}

export async function recordAuditAction(workId:string|null,action:string,justification:string,actor='DEMO_AUDITOR'):Promise<boolean>{if(isSupabaseConfigured&&supabase){try{const{error}=await withTimeout(supabase.from('drishti_audit_trail').insert({work_id:workId,actor,action_executed:action,justification_log:justification}),5000);if(!error)return true;}catch(err){console.error('Audit trail write failed:',err);}}const existing=JSON.parse(localStorage.getItem(DEMO_AUDIT_KEY)||'[]') as AuditTrailEntry[];existing.unshift({audit_id:crypto.randomUUID(),work_id:workId,actor,action_executed:action,justification_log:justification,created_at:new Date().toISOString()});localStorage.setItem(DEMO_AUDIT_KEY,JSON.stringify(existing.slice(0,100)));return false;}
export async function fetchAuditTrail(workId?:string):Promise<AuditTrailEntry[]>{if(isSupabaseConfigured&&supabase){try{let q=supabase.from('drishti_audit_trail').select('*').order('created_at',{ascending:false}).limit(50);if(workId)q=q.eq('work_id',workId);const{data,error}=await withTimeout(q,5000);if(!error)return(data||[]) as AuditTrailEntry[];}catch{}}const e=JSON.parse(localStorage.getItem(DEMO_AUDIT_KEY)||'[]') as AuditTrailEntry[];return workId?e.filter(x=>x.work_id===workId):e;}

export async function updateWorkOrderStatus(workId:string,status:'frozen'|'under_review'|'cleared',action:string,justification:string):Promise<void>{const orders=demoOrders(),order=orders.find(o=>o.work_id===workId);if(order){order.status=status;order.funds_frozen=status==='frozen'?order.budget:0;saveDemo(orders);}let persisted=false;if(isSupabaseConfigured&&supabase){try{const{error}=await withTimeout(supabase.from('work_orders').update({status,funds_frozen:status==='frozen'?(order?.budget??0):0}).eq('work_id',workId),5000);persisted=!error;}catch{}}await recordAuditAction(workId,action,`${justification}${persisted?'':' (Demo-safe local state retained; backend persistence unavailable.)'}`);}
export async function fetchCollusionNetwork():Promise<CollusionNetwork>{if(isSupabaseConfigured&&supabase){try{const[n,e]=await Promise.all([supabase.from('graph_nodes').select('*'),supabase.from('graph_edges').select('*')]);if(!n.error&&!e.error)return{nodes:(n.data||[]) as GraphNode[],edges:(e.data||[]) as GraphEdge[]};}catch{}}return DEMO_NETWORK;}

const demoVision=(workId:string):VisionForensics=>{const s=localStorage.getItem(`${DEMO_VISION_KEY}-${workId}`);if(s)return JSON.parse(s);return{id:`vision-${workId}`,work_id:workId,contractor_photo_url:null,gps_coordinates:'12.9716° N, 77.5946° E · Bengaluru',gps_verified:true,timestamp_verified:true,shadow_geometry_score:78.5,duplicate_detected:false,ai_status:'ready',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};};
export async function fetchVisionForensics(workId:string):Promise<VisionForensics|null>{if(isSupabaseConfigured&&supabase){try{const{data,error}=await supabase.from('vision_forensics').select('*').eq('work_id',workId).maybeSingle();if(!error)return data as VisionForensics|null;}catch{}}return demoVision(workId);}
export async function uploadMilestonePhoto(file:File,workId:string):Promise<{publicUrl:string}>{if(isSupabaseConfigured&&supabase){const ext=file.name.split('.').pop()?.toLowerCase()||'jpg',path=`public/${workId}_progress.${ext}`;try{const{error}=await supabase.storage.from('construction-milestones').upload(path,file,{upsert:true});if(!error){const{data:u}=supabase.storage.from('construction-milestones').getPublicUrl(path);await supabase.from('vision_forensics').update({contractor_photo_url:u.publicUrl,ai_status:'analyzing',updated_at:new Date().toISOString()}).eq('work_id',workId);return{publicUrl:u.publicUrl};}}catch{}}const publicUrl=URL.createObjectURL(file);localStorage.setItem(`${DEMO_VISION_KEY}-${workId}`,JSON.stringify({...demoVision(workId),contractor_photo_url:publicUrl,ai_status:'analyzing',updated_at:new Date().toISOString()}));return{publicUrl};}
export async function updateVisionForensicsResults(workId:string,results:Partial<Pick<VisionForensics,'shadow_geometry_score'|'gps_verified'|'timestamp_verified'|'duplicate_detected'|'ai_status'>>):Promise<void>{if(isSupabaseConfigured&&supabase){try{const{error}=await supabase.from('vision_forensics').update({...results,updated_at:new Date().toISOString()}).eq('work_id',workId);if(!error)return;}catch{}}localStorage.setItem(`${DEMO_VISION_KEY}-${workId}`,JSON.stringify({...demoVision(workId),...results,updated_at:new Date().toISOString()}));}

export async function triggerAIPipeline(workId:string,mode:'freeze'|'vision'='freeze'):Promise<AIPipelineResponse>{
 if(isSupabaseConfigured&&supabase){const key=import.meta.env.VITE_SUPABASE_ANON_KEY as string;try{const response=await withTimeout(fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/audit-pipeline`,{method:'POST',headers:{'Content-Type':'application/json',apikey:key,Authorization:`Bearer ${key}`},body:JSON.stringify({work_id:workId,mode})}),8000);const data=await response.json().catch(()=>({}));if(response.ok&&data.success)return data as AIPipelineResponse;}catch(err){console.error('Remote AI pipeline unavailable:',err);}}
 const orders=demoOrders(),order=orders.find(o=>o.work_id===workId);if(!order)throw new Error(`Work order ${workId} not found`);await new Promise(r=>setTimeout(r,350));
 if(mode==='vision'){const score=workId==='alert-001'?66.4:78.5,duplicate=workId==='alert-003',frozen=score<70;localStorage.setItem(`${DEMO_VISION_KEY}-${workId}`,JSON.stringify({...demoVision(workId),shadow_geometry_score:score,gps_verified:true,timestamp_verified:true,duplicate_detected:duplicate,ai_status:frozen?'funds_frozen':'completed',updated_at:new Date().toISOString()}));if(frozen){order.status='frozen';order.funds_frozen=order.budget;saveDemo(orders);await recordAuditAction(workId,'FUNDS_FROZEN',`Vision forensic anomaly score ${score} triggered a milestone hold.`);}return{success:true,work_id:workId,mode,status:frozen?'FUNDS_FROZEN':'COMPLETED',funds_frozen:frozen?order.budget:false,message:frozen?`Vision anomaly detected (${score}%). Funds frozen.`:`Vision analysis completed (${score}%).`,shadow_geometry_score:score,gps_verified:true,timestamp_verified:true,duplicate_detected:duplicate};}
 const scored=calculateRisk(order);order.risk_score=scored.riskScore;order.risk_level=riskFor(scored.riskScore);order.status=scored.riskScore>=75?'frozen':'under_review';order.funds_frozen=order.status==='frozen'?order.budget:0;saveDemo(orders);await recordAuditAction(workId,order.status==='frozen'?'FUNDS_FROZEN':'AI_REVIEW_FLAGGED',`Isolation Forest + compliance engine scored ${scored.riskScore}/100. ${scored.explanations.join('; ')||'No dominant rule signal.'}`);return{success:true,work_id:workId,status:order.status==='frozen'?'FUNDS_FROZEN':'UNDER_REVIEW',funds_frozen:order.funds_frozen,risk_score:scored.riskScore,risk_level:scored.riskLevel,model:scored.model,explanations:scored.explanations,message:`DRISHTI anomaly model completed: risk ${scored.riskScore}/100.`};
}
export async function triggerPendingAudits(workIds:string[]):Promise<AIPipelineResponse[]>{const results:AIPipelineResponse[]=[];for(const id of workIds)results.push(await triggerAIPipeline(id,'freeze'));return results;}
