import { Database, ExternalLink, ShieldCheck, Users, WalletCards } from 'lucide-react';

const allocations = [
  { mp: 'DR C N MANJUNATH', constituency: 'BANGALORE RURAL', amount: 147000000 },
  { mp: 'P C Mohan', constituency: 'BANGALORE CENTRAL', amount: 159995711.11 },
  { mp: 'SHOBHA KARANDLAJE', constituency: 'BANGALORE NORTH', amount: 147000000 },
  { mp: 'Shri LS Tejasvi Surya', constituency: 'BANGALORE SOUTH', amount: 147000000 },
];
const formatCr=(n:number)=>`₹${(n/10000000).toFixed(2)} Cr`;

export function AllocationSnapshot(){
 const total=allocations.reduce((s,x)=>s+x.amount,0);
 return <section className="rounded-2xl border border-slate-800 bg-slate-900/80 overflow-hidden"><div className="p-5 border-b border-slate-800 flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Database className="w-4 h-4 text-emerald-400"/><h2 className="text-sm font-bold text-white">Official Allocation Baseline</h2><span className="text-[9px] rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 px-2 py-0.5">SOURCE DATA</span></div><p className="text-[10px] text-slate-500 mt-1">Bangalore records from the SIH-provided MPLADS public-dashboard CSV. Allocation data is kept separate from project-level audit scenarios.</p></div><a href="https://mplads.mospi.gov.in/digigov/dashboard.html" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-[10px] text-amber-400 hover:text-amber-300">Open source <ExternalLink className="w-3 h-3"/></a></div><div className="grid grid-cols-1 lg:grid-cols-3 gap-4 p-5"><div className="rounded-xl bg-slate-950/60 border border-slate-800 p-4"><div className="flex items-center gap-2 text-[10px] text-slate-500 uppercase tracking-widest"><Users className="w-3.5 h-3.5"/>MPs in supplied extract</div><div className="text-2xl font-black text-white mt-2">4</div><p className="text-[10px] text-slate-600 mt-1">Bangalore constituencies</p></div><div className="rounded-xl bg-slate-950/60 border border-slate-800 p-4"><div className="flex items-center gap-2 text-[10px] text-slate-500 uppercase tracking-widest"><WalletCards className="w-3.5 h-3.5"/>Bangalore allocation</div><div className="text-2xl font-black text-amber-300 mt-2">{formatCr(total)}</div><p className="text-[10px] text-slate-600 mt-1">Sum of four supplied constituency rows</p></div><div className="rounded-xl bg-slate-950/60 border border-slate-800 p-4"><div className="flex items-center gap-2 text-[10px] text-slate-500 uppercase tracking-widest"><ShieldCheck className="w-3.5 h-3.5"/>Data lineage</div><div className="text-sm font-bold text-emerald-300 mt-3">Verified input layer</div><p className="text-[10px] text-slate-600 mt-1">No project-level facts inferred from this allocation file</p></div></div><div className="px-5 pb-5 space-y-2">{allocations.map(a=><div key={a.constituency} className="grid grid-cols-[1.3fr_1fr_auto] gap-3 items-center rounded-lg bg-slate-950/50 px-3 py-2.5"><div className="text-xs font-semibold text-slate-300 truncate">{a.mp}</div><div className="text-[10px] text-slate-500 truncate">{a.constituency}</div><div className="text-xs font-bold text-white">{formatCr(a.amount)}</div></div>)}</div></section>;
}
