import { useMemo, useRef, useState } from 'react';
import { AlertTriangle, ArrowUpRight, BarChart3, CheckCircle2, ClipboardCheck, Database, FileSearch, Gauge, Network, ShieldCheck, Sparkles, UploadCloud } from 'lucide-react';
import type { WorkOrder } from '@/services/auditService';
import { fetchWorkOrders, recordAuditAction, updateWorkOrderStatus, upsertUploadedWorkOrders } from '@/services/auditService';

type Tab='hub'|'compliance'|'early'|'agency'|'evidence'|'model';
const num=(v:unknown)=>Number(v||0); const pct=(v:number)=>`${Math.round(Math.max(0,Math.min(100,v)))}%`;
const clean=(v:string|undefined)=>Number(String(v??'').replace(/[₹,\s%]/g,''))||0;
const key=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]/g,'');
const pick=(r:Record<string,string>, names:string[])=>{const wanted=names.map(key);const k=Object.keys(r).find(x=>wanted.includes(key(x)));return k?r[k]:'';};
function csv(text:string){const out:string[][]=[];let row:string[]=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell.trim());cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(Boolean))out.push(row);row=[];cell='';continue}cell+=c}row.push(cell.trim());if(row.some(Boolean))out.push(row);return out;}

export function AuditCommandCenter({workOrders:initial}:{workOrders:WorkOrder[]}){
 const [orders,setOrders]=useState(initial),[tab,setTab]=useState<Tab>('hub'),[selectedId,setSelectedId]=useState(initial[0]?.work_id||''),[message,setMessage]=useState('');
 const input=useRef<HTMLInputElement>(null); const selected=useMemo(()=>orders.find(w=>w.work_id===selectedId)||orders[0],[orders,selectedId]);
 const high=orders.filter(w=>w.risk_level==='high'),medium=orders.filter(w=>w.risk_level==='medium');
 const compliance=orders.map(w=>{const gap=Math.max(0,num(w.expected_progress_percentage)-num(w.physical_progress_percentage));return{w,score:Math.round(Math.max(0,Math.min(100,100-gap*.5-(num(w.delay_days)>0?12:0)-(w.is_demo_data?12:0))))}});
 const avg=compliance.length?Math.round(compliance.reduce((s,x)=>s+x.score,0)/compliance.length):0;
 const agencies=useMemo(()=>{const m=new Map<string,{n:number,r:number,d:number}>();orders.forEach(w=>{const a=w.agency||w.contractor||'Unspecified agency',x=m.get(a)||{n:0,r:0,d:0};x.n++;x.r+=num(w.risk_score);x.d+=num(w.delay_days);m.set(a,x)});return [...m].map(([name,x])=>({name,count:x.n,risk:Math.round(x.r/x.n),delay:Math.round(x.d/x.n)})).sort((a,b)=>b.risk-a.risk).slice(0,8)},[orders]);
 const refresh=async()=>{const x=await fetchWorkOrders();setOrders(x);if(!selectedId&&x[0])setSelectedId(x[0].work_id)};
 const importFile=async(file:File)=>{setMessage(`Validating ${file.name}…`);try{const rows=csv(await file.text());if(rows.length<2)throw Error('CSV has no data rows.');const h=rows[0];const mapped=rows.slice(1).map((v,i)=>{const r:Record<string,string>={};h.forEach((x,j)=>r[x]=v[j]||'');return{work_id:pick(r,['work_id','workid','project_id','projectid'])||`UPLOAD-${Date.now()}-${i}`,title:pick(r,['title','work_title','project_title'])||`Imported MPLADS work ${i}`,ward_name:pick(r,['ward_name','ward','district','constituency'])||'Unspecified',contractor:pick(r,['contractor','contractor_name','vendor'])||'Unspecified',agency:pick(r,['agency','implementing_agency','executing_agency'])||'Unspecified',work_category:pick(r,['work_category','category','asset_category'])||'Infrastructure',budget:clean(pick(r,['budget','sanctioned_cost','sanctioned_amount','estimated_cost','cost_estimate'])),total_expenditure:clean(pick(r,['total_expenditure','expenditure','spent','actual_expenditure'])),total_payments_released:clean(pick(r,['total_payments_released','payments','payments_released','payment'])),physical_progress_percentage:clean(pick(r,['physical_progress_percentage','physical_progress','progress'])),expected_progress_percentage:clean(pick(r,['expected_progress_percentage','expected_progress'])),target_date:pick(r,['target_date','completion_date','expected_completion']),delay_days:clean(pick(r,['delay_days','delay'])),duplicate_similarity:clean(pick(r,['duplicate_similarity','duplicate_score'])),contractor_repeat_rate:clean(pick(r,['contractor_repeat_rate','repeat_rate'])),date:pick(r,['date','sanction_date','work_date'])||new Date().toISOString().slice(0,10),mp_name:pick(r,['mp_name','mp','member_of_parliament']),constituency:pick(r,['constituency']),is_demo_data:false}}).filter(x=>x.budget>0||x.total_expenditure>0);if(!mapped.length)throw Error('No usable work rows. Include a Work ID and budget/sanctioned cost.');const res=await upsertUploadedWorkOrders(mapped);await refresh();setTab('hub');setMessage(`${res.count} work record(s) validated and audited${res.persisted?' and persisted to the backend.':' in demo-safe local storage.'}`)}catch(e){setMessage(e instanceof Error?e.message:'Import failed.')}};
 const action=async(name:string)=>{if(!selected)return;if(name==='Mark under review')await updateWorkOrderStatus(selected.work_id,'under_review','MARKED_UNDER_REVIEW','Officer review initiated from DRISHTI command centre.');else await recordAuditAction(selected.work_id,name.toUpperCase().replace(/ /g,'_'),`Review intent created for ${selected.work_id}.`);await refresh();setMessage(`${name} recorded for ${selected.work_id}.`)};
 const tabs:[Tab,string,typeof Database][]=[['hub','Audit Hub',Gauge],['compliance','Compliance',ClipboardCheck],['early','Early Warning',AlertTriangle],['agency','Agency Intelligence',Network],['evidence','Evidence Locker',FileSearch],['model','AI Governance',ShieldCheck]];
 return <div className="space-y-4 sm:space-y-6"><input ref={input} type="file" accept=".csv,text/csv" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.currentTarget.value=''}}/>
 <section className="rounded-2xl border border-amber-500/20 bg-gradient-to-br from-slate-900 via-slate-900 to-amber-950/10 p-4 sm:p-6 shadow-xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-amber-400"/><h2 className="text-lg font-bold text-white">MPLADS AI Audit Command Centre</h2><span className="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-1 text-[9px] uppercase tracking-wider text-emerald-300">END-TO-END</span></div><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-400">Data quality → anomaly signals → evidence → risk → human action, with a traceable audit trail.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>input.current?.click()} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-xs text-slate-300"><UploadCloud className="h-4 w-4"/>Import work dataset</button><button onClick={()=>setTab('early')} className="inline-flex items-center gap-2 rounded-xl bg-amber-400 px-3 py-2 text-xs font-semibold text-slate-950"><ArrowUpRight className="h-4 w-4"/>Open investigation queue</button></div></div>{message&&<div className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/5 px-3 py-2 text-[11px] text-amber-200">{message}</div>}</section>
 <div className="grid grid-cols-2 gap-2 md:grid-cols-4">{[['Works monitored',orders.length,Database],['High risk',high.length,AlertTriangle],['Medium risk',medium.length,BarChart3],['Compliance score',avg,ClipboardCheck]].map(([l,v,I])=><div key={String(l)} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-slate-500">{l}</span><I className="h-4 w-4 text-slate-600"/></div><p className="mt-2 text-xl font-bold text-white">{l==='Compliance score'?pct(Number(v)):v}</p></div>)}</div>
 <div className="flex gap-2 overflow-x-auto rounded-xl border border-slate-800 bg-slate-900/60 p-2">{tabs.map(([id,l,I])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-xs ${tab===id?'bg-amber-500/10 text-amber-300 border border-amber-500/20':'text-slate-400 hover:text-white'}`}><I className="h-4 w-4"/>{l}</button>)}</div>
 {tab==='hub'&&<div className="grid grid-cols-1 xl:grid-cols-3 gap-4"><div className="xl:col-span-2 rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="text-sm font-semibold text-white">Unified risk pipeline</h3><div className="mt-5 grid grid-cols-2 md:grid-cols-4 gap-2">{['Ingest & validate','Rules + ML','Evidence fusion','Risk + action'].map((x,i)=><div key={x} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="text-[9px] text-amber-400">0{i+1}</div><p className="mt-2 text-xs font-semibold text-slate-200">{x}</p><div className="mt-3 h-1.5 rounded-full bg-slate-800"><div className="h-full w-full rounded-full bg-emerald-400"/></div></div>)}</div><p className="mt-4 text-[10px] leading-5 text-slate-500">Official/supplied allocation data stays distinct from imported work records and demo scenarios. <span className="text-amber-300">A flag is an audit signal, not a fraud finding.</span></p></div><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="text-sm font-semibold text-white">Data quality gate</h3>{['Schema validation','Financial fields','Duplicate record check','Coordinate coverage','Evidence completeness'].map((x,i)=><div key={x} className="mt-3 flex justify-between border-b border-slate-800 pb-2 text-xs"><span className="text-slate-400">{x}</span><span className={i===0||i===2?'text-emerald-400':'text-amber-400'}>{i===0||i===2?'READY':'REVIEW'}</span></div>)}</div></div>}
 {tab==='compliance'&&<div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between"><h3 className="text-sm font-semibold text-white">Automated compliance matrix</h3><b className="text-sm text-emerald-400">{pct(avg)} portfolio</b></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-slate-800 text-[10px] uppercase text-slate-600"><th className="p-2">Work</th><th className="p-2">Progress</th><th className="p-2">Schedule</th><th className="p-2">Financial</th><th className="p-2">Source</th><th className="p-2">Score</th></tr></thead><tbody>{compliance.slice(0,20).map(({w,score})=><tr key={w.work_id} className="border-b border-slate-800/70"><td className="p-2 text-slate-300">{w.work_id}</td><td className="p-2">{num(w.physical_progress_percentage)>=num(w.expected_progress_percentage)?'✓':'⚠'}</td><td className="p-2">{num(w.delay_days)>0?'⚠':'✓'}</td><td className="p-2">{num(w.total_expenditure)<=num(w.budget)?'✓':'⚠'}</td><td className="p-2">{w.is_demo_data?'DEMO':'IMPORTED'}</td><td className="p-2 font-bold text-amber-400">{score}/100</td></tr>)}</tbody></table></div></div>}
 {tab==='early'&&<div className="grid grid-cols-1 xl:grid-cols-2 gap-4"><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="text-sm font-semibold text-white">Risk trajectory & early warning</h3><div className="mt-5 flex items-end gap-2 h-44">{[35,42,48,57,64,72,81].map((v,i)=><div key={i} className="flex-1"><div className="rounded-t bg-amber-400/70" style={{height:`${v}%`}}/><p className="mt-1 text-center text-[9px] text-slate-600">W{i+1}</p></div>)}</div><div className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-xs text-amber-200">Illustrative trajectory — production forecasting requires authorised historical MPLADS work histories and calibration.</div></div><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="text-sm font-semibold text-white">Priority queue</h3><div className="mt-4 space-y-2">{[...high,...medium].slice(0,10).map(w=><button key={w.work_id} onClick={()=>{setSelectedId(w.work_id);setTab('evidence')}} className="w-full rounded-xl border border-slate-800 bg-slate-950 p-3 text-left"><div className="flex justify-between"><b className="text-xs text-slate-200">{w.work_id}</b><b className="text-xs text-amber-300">{Math.round(num(w.risk_score))}/100</b></div><p className="mt-1 text-[10px] text-slate-500">{w.work_title||w.title||'Monitored work'} · {num(w.delay_days)} delay days</p></button>)}</div></div></div>}
 {tab==='agency'&&<div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="text-sm font-semibold text-white">Implementing agency intelligence</h3><p className="mt-1 text-[10px] text-slate-500">Aggregate risk and delay signals; never a misconduct determination.</p><div className="mt-4 grid gap-2">{agencies.map(a=><div key={a.name} className="grid grid-cols-[1fr_auto_auto_auto] gap-3 items-center rounded-xl border border-slate-800 bg-slate-950 p-3"><div><b className="text-xs text-slate-200">{a.name}</b><p className="text-[10px] text-slate-600">{a.count} work(s)</p></div><span className="text-[10px] text-slate-500">Risk <b className="text-slate-300">{a.risk}</b></span><span className="text-[10px] text-slate-500">Delay <b className="text-slate-300">{a.delay}d</b></span><b className={`text-[10px] ${a.risk>=75?'text-red-400':a.risk>=50?'text-amber-400':'text-emerald-400'}`}>{a.risk>=75?'REVIEW':a.risk>=50?'WATCH':'NORMAL'}</b></div>)}</div></div>}
 {tab==='evidence'&&<div className="grid grid-cols-1 xl:grid-cols-3 gap-4"><div className="xl:col-span-2 rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="text-sm font-semibold text-white">Evidence locker</h3><select value={selected?.work_id||''} onChange={e=>setSelectedId(e.target.value)} className="mt-4 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-xs text-slate-300">{orders.map(w=><option key={w.work_id} value={w.work_id}>{w.work_id} · {w.work_title||w.title}</option>)}</select>{selected&&<div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-2">{[['Financial',num(selected.total_expenditure)<=num(selected.budget)?'Consistent':'Review'],['Progress',`${num(selected.physical_progress_percentage)}%`],['Payments',`₹${(num(selected.total_payments_released)/10000000).toFixed(2)} Cr`],['Satellite','Field Hub']].map(([a,b])=><div key={a} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><p className="text-[10px] text-slate-600">{a}</p><p className="mt-2 text-xs font-bold text-slate-200">{b}</p></div>)}</div>}</div><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="text-sm font-semibold text-white">Investigation action</h3><p className="mt-2 text-[10px] leading-5 text-slate-500">Demo-safe actions are persisted to the audit trail.</p><div className="mt-4 space-y-2">{['Request evidence','Assign investigator','Mark under review','Generate audit case'].map(x=><button key={x} onClick={()=>void action(x)} className="w-full rounded-xl border border-slate-800 bg-slate-950 px-3 py-2.5 text-left text-xs text-slate-300">{x}</button>)}</div>{selected&&<p className="mt-3 text-[10px] text-slate-600">Selected: {selected.work_id}</p>}</div></div>}
 {tab==='model'&&<div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="text-sm font-semibold text-white">AI model card</h3>{[['Model','Isolation Forest + deterministic rules'],['Training corpus','Synthetic administrative-pattern corpus'],['Fusion','65% ML + 35% rules'],['Decision','Human review required']].map(([a,b])=><div key={a} className="flex justify-between gap-3 border-b border-slate-800 py-3 text-xs"><span className="text-slate-500">{a}</span><span className="text-right text-slate-300">{b}</span></div>)}</div><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="text-sm font-semibold text-white">Governance controls</h3>{['Model provenance displayed','Risk explanation retained','Audit action trail enabled','Fraud is never auto-determined'].map(x=><div key={x} className="mt-3 flex gap-2 text-xs text-slate-400"><CheckCircle2 className="h-4 w-4 text-emerald-400"/>{x}</div>)}</div></div>}
 </div>;
}
