import { useEffect, useMemo, useState } from 'react';
import { Bot, Loader2, Send, ShieldCheck, Sparkles, X } from 'lucide-react';
import { fetchWorkOrders } from '@/services/auditService';
import type { WorkOrder } from '@/services/auditService';

interface Props { workOrders?: WorkOrder[]; selectedWork?: WorkOrder | null; }
const QUICK_PROMPTS = ['Summarize the highest-risk cases and explain why they need attention first.','Explain the financial and progress signals for the riskiest project.','What should an audit officer verify before taking action?'];
function compactRecord(work: WorkOrder) { return { work_id: work.work_id, title: work.work_title || 'Monitored work', constituency: work.constituency, budget: work.budget, expenditure: work.total_expenditure, payments: work.total_payments_released, physical_progress: work.physical_progress_percentage, expected_progress: work.expected_progress_percentage, delay_days: work.delay_days, risk_score: work.risk_score, risk_level: work.risk_level, status: work.status, is_demo_data: work.is_demo_data }; }

export function AuditCopilot({ workOrders, selectedWork }: Props) {
  const [open, setOpen] = useState(false); const [records, setRecords] = useState<WorkOrder[]>(workOrders || []); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (workOrders) { setRecords(workOrders); return; } void fetchWorkOrders().then(setRecords).catch(() => setRecords([])); }, [workOrders]);
  const context = useMemo(() => { const selected = selectedWork ? [selectedWork] : []; const rest = records.filter((w) => w.work_id !== selectedWork?.work_id); return [...selected, ...rest].slice(0, 12).map(compactRecord); }, [records, selectedWork]);
  const ask = async (prompt = question) => { const clean = prompt.trim(); if (!clean || busy) return; setBusy(true); setError(''); setAnswer(''); try { const response = await fetch('/api/audit-copilot', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question: clean, selectedWork: selectedWork ? compactRecord(selectedWork) : null, records: context }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error || 'The AI service could not answer this request.'); setAnswer(String(payload.answer || 'No answer was returned.')); setQuestion(''); } catch (err) { setError(err instanceof Error ? err.message : 'The AI service is unavailable.'); } finally { setBusy(false); } };
  return <div className="fixed bottom-4 right-4 z-[70]">
    {!open && <button type="button" onClick={() => setOpen(true)} className="flex items-center gap-2 rounded-full bg-emerald-700 px-4 py-3 text-xs font-bold text-white shadow-xl shadow-emerald-900/20 transition hover:bg-emerald-800"><Bot className="h-4 w-4" /> AI Audit Copilot</button>}
    {open && <section className="w-[min(92vw,430px)] overflow-hidden rounded-2xl border border-emerald-200 bg-white shadow-2xl">
      <div className="flex items-center justify-between border-b border-slate-200 bg-emerald-50 px-4 py-3"><div className="flex items-center gap-2"><div className="rounded-lg bg-white p-2"><Bot className="h-4 w-4 text-emerald-700" /></div><div><div className="flex items-center gap-2"><h2 className="text-xs font-bold text-slate-900">DRISHTI AI Audit Copilot</h2><span className="rounded-full bg-white px-2 py-0.5 text-[8px] font-bold uppercase text-emerald-700">LLM</span></div><p className="text-[9px] text-slate-500">Grounded audit assistance</p></div></div><button type="button" onClick={() => setOpen(false)} className="rounded-lg p-2 text-slate-400 hover:bg-white hover:text-slate-700"><X className="h-4 w-4" /></button></div>
      <div className="max-h-[65vh] overflow-y-auto p-4"><div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-[10px] leading-5 text-slate-600"><ShieldCheck className="mr-1 inline h-3.5 w-3.5 text-emerald-600" />The assistant uses the dashboard's available audit records and treats anomalies as screening signals, not proof of fraud.</div>
        <div className="mt-3 flex flex-wrap gap-1.5">{QUICK_PROMPTS.map((prompt) => <button key={prompt} type="button" onClick={() => void ask(prompt)} disabled={busy} className="rounded-full border border-slate-200 bg-white px-2.5 py-1.5 text-[9px] text-slate-600 hover:border-emerald-300 hover:bg-emerald-50 disabled:opacity-50">{prompt}</button>)}</div>
        <div className="mt-3 flex gap-2"><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void ask(); }} placeholder="Ask about risk, delay, payments or next steps…" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-[10px] text-slate-900 outline-none focus:border-emerald-400" /><button type="button" onClick={() => void ask()} disabled={!question.trim() || busy} className="rounded-xl bg-emerald-700 px-3 py-2 text-white disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}</button></div>
        {busy && <div className="mt-3 rounded-xl bg-emerald-50 p-3 text-[10px] text-emerald-800"><Sparkles className="mr-1 inline h-3.5 w-3.5" />Analysing supplied audit context…</div>}
        {error && <div className="mt-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-[10px] text-rose-700">{error}<div className="mt-1 text-[9px]">Configure GEMINI_API_KEY on the deployment to enable live LLM responses.</div></div>}
        {answer && <div className="mt-3 rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="mb-2 flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-emerald-700"><Sparkles className="h-3 w-3" />Grounded AI response</div><div className="whitespace-pre-wrap text-[10px] leading-5 text-slate-700">{answer}</div></div>}
      </div>
    </section>}
  </div>;
}
