import { Snowflake, ClipboardCheck, CheckCircle2, X, FileBadge2, ScanEye, Network, Loader2, AlertCircle, Printer, History, ShieldAlert, Clock3, IndianRupee, CopyCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { WorkOrder, AuditTrailEntry } from '@/services/auditService';
import { updateWorkOrderStatus, fetchAuditTrail, recordAuditAction } from '@/services/auditService';
import { BoQAuditTab } from './BoQAuditTab';
import { VisionAuditTab } from './VisionAuditTab';
import { CollusionGraphTab } from './CollusionGraphTab';
import { boqItems, formatCurrency } from '@/lib/mockData';
interface DeepDivePanelProps { alert: WorkOrder | null; onClose: () => void; contractorImage: string; aiBaselineImage: string; onFundsFrozen?: (workId: string) => void; }
type TabId = 'boq' | 'vision' | 'collusion';
const tabs: { id: TabId; label: string; icon: typeof Snowflake }[] = [{ id:'boq',label:'BoQ & Cost Audit',icon:FileBadge2 },{ id:'vision',label:'Photo / Spatial Audit',icon:ScanEye },{ id:'collusion',label:'Network Analysis',icon:Network }];
export function DeepDivePanel({ alert, onClose, aiBaselineImage, onFundsFrozen }: DeepDivePanelProps) {
 const [activeTab,setActiveTab]=useState<TabId>('boq'); const [actionResult,setActionResult]=useState<string|null>(null); const [actionError,setActionError]=useState<string|null>(null); const [isProcessing,setIsProcessing]=useState(false); const [frozenStatus,setFrozenStatus]=useState(false); const [logs,setLogs]=useState<AuditTrailEntry[]>([]);
 useEffect(()=>{if(alert)void fetchAuditTrail(alert.work_id).then(setLogs)},[alert]);
 if(!alert)return null;
 const isFrozen=frozenStatus||alert.status==='frozen'; const expenditure=Number(alert.total_expenditure??0); const payments=Number(alert.total_payments_released??0); const progress=Number(alert.physical_progress_percentage??0); const expected=Number(alert.expected_progress_percentage??0); const divergence=alert.budget>0?Math.max(0,((payments-expenditure)/alert.budget)*100):0;
 const signals=[{label:'Cost / BoQ outlier',value:'Peer benchmark',icon:IndianRupee,active:true},{label:'Execution stall',value:progress<expected-20?'Detected':'Monitor',icon:Clock3,active:progress<expected-20},{label:'Payment divergence',value:divergence>10?'Review':'Normal',icon:ShieldAlert,active:divergence>10},{label:'Duplicate similarity',value:'Similarity scan',icon:CopyCheck,active:true}];
 const refreshLogs=async()=>setLogs(await fetchAuditTrail(alert.work_id));
 const handleFreezeFunds=async()=>{setIsProcessing(true);setActionError(null);setActionResult(null);try{await updateWorkOrderStatus(alert.work_id,'frozen','FUNDS_FROZEN','Auditor froze milestone funds after reviewing the risk evidence.');setFrozenStatus(true);setActionResult(`Funds frozen: ${formatCurrency(alert.budget)} held pending audit review.`);onFundsFrozen?.(alert.work_id);await refreshLogs()}catch(err){setActionError(err instanceof Error?err.message:'Failed to freeze funds')}finally{setIsProcessing(false)}};
 const handleAction=async(action:'MANUAL_PHYSICAL_AUDIT'|'APPROVED')=>{setIsProcessing(true);setActionError(null);setActionResult(null);try{const status=action==='APPROVED'?'cleared':'under_review';await updateWorkOrderStatus(alert.work_id,status,action,action==='APPROVED'?'Auditor approved release after review.':'Auditor requested field verification based on risk evidence.');setActionResult(action==='APPROVED'?'Funds approved & release decision recorded.':'Manual physical audit requested. Work order moved to Under Review.');await refreshLogs()}catch(err){setActionError(err instanceof Error?err.message:'Unable to record action')}finally{setIsProcessing(false)}};
 const generateCertificate=async()=>{setIsProcessing(true);setActionError(null);try{await recordAuditAction(alert.work_id,'AUDIT_CERTIFICATE_GENERATED',`DRISHTI decision-support audit artifact generated for ${alert.work_id}.`);await refreshLogs();const w=window.open('','_blank','width=900,height=700');if(!w)throw new Error('Popup blocked. Allow popups to generate the audit record.');w.document.write(`<html><head><title>DRISHTI Audit Record ${alert.work_id}</title><style>body{font-family:Arial,sans-serif;padding:48px;color:#111}table{border-collapse:collapse;width:100%;margin-top:24px}td,th{border:1px solid #ddd;padding:10px;text-align:left}.risk{font-size:22px;font-weight:700}.note{margin-top:32px;color:#555;font-size:12px}</style></head><body><h1>DRISHTI — AI-Assisted Audit Record</h1><p>SIH demonstration artifact · ${new Date().toLocaleString()}</p><h2>${alert.title}</h2><p>Work ID: ${alert.work_id} · Ward: ${alert.ward_name} · Agency: ${alert.agency} · Contractor: ${alert.contractor}</p><table><tr><th>Sanction / Budget</th><th>Risk Score</th><th>Status</th><th>Funds Held</th></tr><tr><td>${formatCurrency(alert.budget)}</td><td>${alert.risk_score}/100</td><td>${isFrozen?'FUNDS_FROZEN':alert.status}</td><td>${formatCurrency(alert.funds_frozen||0)}</td></tr></table><p class="risk">Decision-support evidence summary</p><p class="note">This is a DRISHTI prototype audit artifact, not a statutory Government of India certificate. Findings are risk signals requiring authorised human review.</p><script>window.onload=()=>window.print()</script></body></html>`);w.document.close();setActionResult('DRISHTI audit record opened in a print-ready window. Choose Save as PDF.')}catch(err){setActionError(err instanceof Error?err.message:'Audit record generation failed')}finally{setIsProcessing(false)}};
 const actions=[{label:'Freeze Funds',icon:Snowflake,action:handleFreezeFunds,disabled:isProcessing||isFrozen,cls:'amber'},{label:'Request Physical Audit',icon:ClipboardCheck,action:()=>void handleAction('MANUAL_PHYSICAL_AUDIT'),disabled:isProcessing,cls:'blue'},{label:'Approve Release',icon:CheckCircle2,action:()=>void handleAction('APPROVED'),disabled:isProcessing,cls:'emerald'},{label:'Generate Audit Record',icon:Printer,action:()=>void generateCertificate(),disabled:isProcessing,cls:'slate'}] as const; const colorMap:Record<string,string>={amber:'bg-amber-500/10 text-amber-500 border-amber-500/25 hover:bg-amber-500/20',blue:'bg-blue-500/10 text-blue-500 border-blue-500/25 hover:bg-blue-500/20',emerald:'bg-emerald-500/10 text-emerald-500 border-emerald-500/25 hover:bg-emerald-500/20',slate:'bg-slate-500/10 text-slate-500 border-slate-400/20 hover:bg-slate-500/20'}; const riskLevel=alert.risk_level as 'high'|'medium'|'low';
 return <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-end sm:items-center justify-center p-0 sm:p-4">{isProcessing&&<div className="absolute inset-0 z-[60] bg-slate-950/85 backdrop-blur flex flex-col items-center justify-center"><Loader2 className="w-12 h-12 text-amber-400 animate-spin"/><p className="mt-4 text-sm font-semibold text-white">DRISHTI is recording the decision</p><p className="mt-1 text-xs text-slate-400">Updating local audit state and attempting backend persistence…</p></div>}<div className="w-full max-w-6xl h-[96vh] sm:h-auto sm:max-h-[92vh] bg-slate-900 rounded-t-2xl sm:rounded-2xl border border-slate-800 shadow-2xl overflow-hidden flex flex-col">
 <div className="px-4 sm:px-6 py-4 border-b border-slate-800 flex items-start justify-between shrink-0"><div className="min-w-0 pr-3"><div className="flex flex-wrap items-center gap-2 mb-1"><span className={`w-2.5 h-2.5 rounded-full ${riskLevel==='high'?'bg-red-500':riskLevel==='medium'?'bg-amber-500':'bg-emerald-500'}`}/><span className="text-[10px] uppercase tracking-widest text-slate-500">Work Order · {alert.work_id}</span>{isFrozen&&<span className="text-[9px] font-bold text-red-500 bg-red-500/10 border border-red-500/20 px-2 py-0.5 rounded uppercase">Funds Frozen</span>}</div><h2 className="text-base sm:text-lg font-bold text-white truncate">{alert.title}</h2><div className="flex flex-wrap gap-x-4 gap-y-1 mt-1 text-[10px] sm:text-xs text-slate-500"><span>Ward: <b className="text-slate-300">{alert.ward_name}</b></span><span>Agency: <b className="text-slate-300">{alert.agency}</b></span><span>Budget: <b className="text-slate-300">{formatCurrency(alert.budget)}</b></span></div></div><button onClick={onClose} disabled={isProcessing} className="w-9 h-9 shrink-0 rounded-lg bg-slate-800 hover:bg-slate-700 flex items-center justify-center text-slate-400 hover:text-white"><X className="w-5 h-5"/></button></div>
 <div className="px-2 sm:px-6 border-b border-slate-800 overflow-x-auto shrink-0"><div className="flex min-w-max">{tabs.map(tab=>{const Icon=tab.icon;const active=activeTab===tab.id;return <button key={tab.id} onClick={()=>setActiveTab(tab.id)} className={`flex items-center gap-2 px-3 sm:px-4 py-3 text-xs sm:text-sm font-medium border-b-2 whitespace-nowrap ${active?'border-amber-500 text-amber-500':'border-transparent text-slate-500 hover:text-slate-300'}`}><Icon className="w-4 h-4"/>{tab.label}</button>})}</div></div>
 <div className="flex-1 overflow-y-auto p-4 sm:p-6"><div className="grid grid-cols-2 lg:grid-cols-4 gap-2 mb-5">{signals.map(s=>{const Icon=s.icon;return <div key={s.label} className={`rounded-xl border p-3 ${s.active?'border-amber-500/20 bg-amber-500/5':'border-slate-800 bg-slate-950/40'}`}><div className="flex items-center gap-2"><Icon className={`w-4 h-4 ${s.active?'text-amber-500':'text-slate-600'}`}/><span className="text-[9px] uppercase tracking-wider text-slate-500">Signal</span></div><p className="text-[11px] font-semibold text-slate-200 mt-2">{s.label}</p><p className={`text-[10px] mt-0.5 ${s.active?'text-amber-500':'text-slate-500'}`}>{s.value}</p></div>})}</div>{activeTab==='boq'&&<BoQAuditTab items={boqItems}/>} {activeTab==='vision'&&<VisionAuditTab workId={alert.work_id} aiBaselineImage={aiBaselineImage} onFundsFrozen={onFundsFrozen}/>} {activeTab==='collusion'&&<CollusionGraphTab/>}</div>
 <div className="px-4 sm:px-6 py-4 border-t border-slate-800 bg-slate-950/50 shrink-0 max-h-[36vh] overflow-y-auto"><div className="flex flex-wrap items-center gap-2 mb-3"><span className="text-[10px] uppercase tracking-widest text-slate-500">Decision status</span>{isFrozen?<span className="inline-flex items-center gap-1 text-[10px] font-bold text-red-500 bg-red-500/10 border border-red-500/20 px-2.5 py-1 rounded uppercase"><Snowflake className="w-3 h-3"/>FUNDS_FROZEN</span>:<span className="text-[10px] font-medium text-slate-500 bg-slate-800 px-2.5 py-1 rounded capitalize">{alert.status.replace('_',' ')}</span>}</div>{actionResult&&<div className="mb-3 flex items-center gap-2 text-xs text-emerald-500 bg-emerald-500/10 rounded-lg px-3 py-2"><CheckCircle2 className="w-4 h-4 shrink-0"/>{actionResult}</div>}{actionError&&<div className="mb-3 flex items-center gap-2 text-xs text-red-500 bg-red-500/10 rounded-lg px-3 py-2"><AlertCircle className="w-4 h-4 shrink-0"/>{actionError}</div>}<div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-widest text-slate-500">Action Center</p><p className="text-[10px] sm:text-xs text-slate-500 mt-0.5">Human decision · local fallback · auditable decision log</p></div><div className="grid grid-cols-2 sm:flex sm:flex-wrap gap-2">{actions.map(a=>{const Icon=a.icon;return <button key={a.label} type="button" onClick={a.action} disabled={a.disabled} className={`flex items-center justify-center gap-2 px-3 py-2 rounded-lg text-[10px] sm:text-xs font-medium border ${colorMap[a.cls]} ${a.disabled?'opacity-40 cursor-not-allowed':'cursor-pointer'}`}><Icon className="w-3.5 h-3.5"/>{a.label}</button>})}</div></div><div className="mt-4 border-t border-slate-800 pt-3"><div className="flex items-center gap-2 text-xs font-semibold text-slate-300"><History className="w-4 h-4 text-amber-500"/>Audit trail <span className="text-slate-600">({logs.length})</span></div>{logs.length>0&&<div className="mt-2 max-h-20 overflow-y-auto space-y-1">{logs.map(log=><div key={log.audit_id} className="text-[9px] sm:text-[10px] text-slate-500"><span className="text-amber-500">{log.action_executed}</span> · {log.actor} · {new Date(log.created_at).toLocaleString()}</div>)}</div>}</div></div></div></div>;
}
