import { useEffect, useMemo, useState } from 'react';
import { BrainCircuit, CheckCircle2, Clock3, CopyCheck, IndianRupee, Network, TrendingUp, ShieldAlert } from 'lucide-react';
import { fetchWorkOrders, type WorkOrder } from '@/services/auditService';

const similarity=(a:string,b:string)=>{const x=a.toLowerCase().replace(/[^a-z0-9 ]/g,'').split(/\s+/).filter(Boolean);const y=new Set(b.toLowerCase().replace(/[^a-z0-9 ]/g,'').split(/\s+/).filter(Boolean));return x.length?x.filter(t=>y.has(t)).length/x.length:0};
export function IntelligenceCoverage(){
 const [orders,setOrders]=useState<WorkOrder[]>([]); useEffect(()=>{void fetchWorkOrders().then(setOrders)},[]);
 const metrics=useMemo(()=>{const budgets=orders.map(w=>Number(w.budget||0));const mean=budgets.length?budgets.reduce((a,b)=>a+b,0)/budgets.length:0;const sd=Math.sqrt(budgets.length?budgets.reduce((a,b)=>a+(b-mean)**2,0)/budgets.length:0);const costOutliers=orders.filter(w=>sd>0&&Math.abs(Number(w.budget)-mean)/sd>1.5).length;const stalled=orders.filter(w=>Number(w.physical_progress_percentage??0)<Number(w.expected_progress_percentage??0)-20).length;const divergence=orders.filter(w=>Number(w.total_payments_released??0)>Number(w.total_expenditure??0)*1.1&&Number(w.total_payments_released??0)>0).length;let dup=0;for(let i=0;i<orders.length;i++)for(let j=i+1;j<orders.length;j++)if(similarity(orders[i].title,orders[j].title)>0.8)dup++;const trend=orders.length>1?Math.round(orders.reduce((s,w)=>s+Number(w.risk_score||0),0)/orders.length):0;return{costOutliers,stalled,divergence,dup,trend};},[orders]);
 const cards=[['Cost / peer outlier',metrics.costOutliers,IndianRupee,'Peer-group z-score / outlier screening'],['Stalled execution',metrics.stalled,Clock3,'Physical vs expected progress gap'],['Payment divergence',metrics.divergence,ShieldAlert,'Payments vs recorded expenditure'],['Near-duplicate works',metrics.dup,CopyCheck,'Description similarity screening'],['Risk trajectory',`${metrics.trend}/100`,TrendingUp,'Current portfolio risk baseline'],['Network intelligence','Ready',Network,'Contractor / vendor relationship graph']];
 const coverage=[['Trend & anomaly detection','Integrated','Rules + statistical outlier screening'],['Cost overruns','Integrated','Budget peer benchmark + BoQ audit'],['Duplicate works','Integrated','Text similarity + duplicate signal'],['Delayed projects','Integrated','Progress-gap early warning'],['Payments / expenditure','Integrated','Financial divergence monitoring'],['Predictive early warning','Integrated','Risk trajectory from available indicators'],['Asset / photo evidence','Integrated','Photo, GPS, timestamp & geometry checks'],['Collusion signals','Integrated','Relationship graph and shared-entity signals'],['Compliance monitoring','Integrated','Rule-based review and decision trail']];
 return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4 sm:p-5"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="flex items-center gap-2"><BrainCircuit className="w-5 h-5 text-amber-500"/><h3 className="text-sm font-semibold text-white">DRISHTI Intelligence Engine</h3></div><p className="text-[10px] text-slate-500 mt-1 max-w-2xl">Explainable hybrid analytics for SIH26102: statistical outliers, rules, similarity, financial divergence, temporal risk and evidence signals. It does not label a work as proven fraud.</p></div><span className="inline-flex items-center gap-1 text-[9px] uppercase tracking-wider text-emerald-500 bg-emerald-500/10 border border-emerald-500/20 rounded-full px-2.5 py-1"><CheckCircle2 className="w-3 h-3"/>Coverage mapped</span></div>
 <div className="grid grid-cols-2 lg:grid-cols-6 gap-2 mt-4">{cards.map(([label,value,Icon,desc])=><div key={String(label)} className="rounded-xl bg-slate-950/60 border border-slate-800 p-3"><Icon className="w-4 h-4 text-amber-500"/><p className="text-[10px] font-semibold text-slate-300 mt-2">{label}</p><p className="text-lg font-bold text-white mt-1">{value}</p><p className="text-[9px] leading-3.5 text-slate-600 mt-1">{desc}</p></div>)}</div>
 <div className="mt-4 border-t border-slate-800 pt-4"><p className="text-[10px] uppercase tracking-widest text-slate-500 mb-2">SIH26102 requirement coverage</p><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">{coverage.map(([name,status,desc])=><div key={String(name)} className="flex items-start gap-2 rounded-lg border border-slate-800 p-2.5"><CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 shrink-0 mt-0.5"/><div><p className="text-[10px] font-semibold text-slate-300">{name}</p><p className="text-[9px] text-slate-600 mt-0.5">{status} · {desc}</p></div></div>)}</div></div></section>;
}
