import { useEffect, useState } from 'react';
import { X, UserRound, Moon, Sun, Type, Bell, ShieldCheck, Check, RotateCcw } from 'lucide-react';

export interface DrishtiPreferences { theme: 'dark'|'light'; fontSize: 'small'|'medium'|'large'; compact: boolean; notifications: boolean; }
interface Props { user: { name: string; role: string }; onClose: ()=>void; }
const KEY='drishti_preferences';
export function ProfileSettings({ user, onClose }: Props) {
  const [prefs,setPrefs]=useState<DrishtiPreferences>(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'')||{theme:'dark',fontSize:'medium',compact:false,notifications:true}}catch{return {theme:'dark',fontSize:'medium',compact:false,notifications:true}}});
  useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(prefs)); document.documentElement.classList.toggle('light',prefs.theme==='light'); document.documentElement.style.fontSize=prefs.fontSize==='small'?'14px':prefs.fontSize==='large'?'18px':'16px';},[prefs]);
  const update=(p:Partial<DrishtiPreferences>)=>setPrefs(v=>({...v,...p}));
  return <div className="fixed inset-0 z-[80] bg-black/70 backdrop-blur-sm flex justify-end"><div className="w-full max-w-md h-full bg-slate-950 border-l border-slate-800 shadow-2xl overflow-y-auto"><div className="sticky top-0 z-10 bg-slate-950/95 backdrop-blur border-b border-slate-800 p-5 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.22em] text-amber-400">Account</p><h2 className="text-lg font-bold text-white mt-1">Profile & Preferences</h2></div><button onClick={onClose} className="p-2 rounded-lg hover:bg-slate-800 text-slate-400"><X className="w-5 h-5"/></button></div>
    <div className="p-5 space-y-6"><div className="rounded-2xl border border-slate-800 bg-gradient-to-br from-slate-900 to-slate-950 p-5"><div className="flex items-center gap-4"><div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-amber-400 to-emerald-500 flex items-center justify-center text-lg font-black text-slate-950">{user.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h3 className="font-bold text-white">{user.name}</h3><p className="text-xs text-slate-500 mt-1">{user.role}</p><span className="inline-flex items-center gap-1 text-[9px] text-emerald-400 mt-2"><ShieldCheck className="w-3 h-3"/> Demo clearance · Audit workspace</span></div></div></div>
      <section><div className="flex items-center gap-2 text-xs font-semibold text-slate-300 mb-3"><Sun className="w-4 h-4 text-amber-400"/>Appearance</div><div className="grid grid-cols-2 gap-2"><button onClick={()=>update({theme:'light'})} className={`rounded-xl border p-4 text-left ${prefs.theme==='light'?'border-amber-500/50 bg-amber-500/10':'border-slate-800 bg-slate-900'}`}><Sun className="w-4 h-4 mb-2 text-amber-400"/><p className="text-xs font-semibold text-white">Light</p></button><button onClick={()=>update({theme:'dark'})} className={`rounded-xl border p-4 text-left ${prefs.theme==='dark'?'border-amber-500/50 bg-amber-500/10':'border-slate-800 bg-slate-900'}`}><Moon className="w-4 h-4 mb-2 text-indigo-300"/><p className="text-xs font-semibold text-white">Dark</p></button></div></section>
      <section><div className="flex items-center gap-2 text-xs font-semibold text-slate-300 mb-3"><Type className="w-4 h-4 text-emerald-400"/>Text size</div><div className="flex gap-2">{(['small','medium','large'] as const).map(s=><button key={s} onClick={()=>update({fontSize:s})} className={`flex-1 rounded-xl border py-3 text-xs capitalize ${prefs.fontSize===s?'border-amber-500/50 bg-amber-500/10 text-amber-300':'border-slate-800 bg-slate-900 text-slate-400'}`}>{s}</button>)}</div></section>
      <section className="space-y-2"><Setting icon={<Bell className="w-4 h-4"/>} title="Risk notifications" desc="Show alerts for high-risk audit events" value={prefs.notifications} onChange={v=>update({notifications:v})}/><Setting icon={<Type className="w-4 h-4"/>} title="Compact dashboard" desc="Reduce card spacing for dense monitoring" value={prefs.compact} onChange={v=>update({compact:v})}/></section>
      <button onClick={()=>update({theme:'dark',fontSize:'medium',compact:false,notifications:true})} className="w-full rounded-xl border border-slate-800 bg-slate-900 py-3 text-xs text-slate-400 hover:text-white flex items-center justify-center gap-2"><RotateCcw className="w-3.5 h-3.5"/>Reset preferences</button>
      <p className="text-[10px] leading-5 text-slate-600">Preferences are stored locally in this browser for the prototype. Production deployment can bind them to authenticated user profiles.</p>
    </div></div></div>;
}
function Setting({icon,title,desc,value,onChange}:{icon:React.ReactNode;title:string;desc:string;value:boolean;onChange:(v:boolean)=>void}){return <button onClick={()=>onChange(!value)} className="w-full flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4 text-left"><span className="text-slate-500">{icon}</span><span className="flex-1"><span className="block text-xs font-semibold text-slate-300">{title}</span><span className="block text-[10px] text-slate-600 mt-1">{desc}</span></span><span className={`w-9 h-5 rounded-full p-0.5 transition ${value?'bg-emerald-500':'bg-slate-700'}`}><span className={`block w-4 h-4 rounded-full bg-white transition ${value?'translate-x-4':'translate-x-0'}`}>{value&&<Check className="w-4 h-4 text-emerald-700"/>}</span></span></button>}
